#ifndef LINE2_LIBRARY_H
#define LINE2_LIBRARY_H

const char* LINES_7_SYLLABLES_LINE2[] = {
    "Les étoiles se dispersent",
    "Un parfum léger s’efface",
    "Les vagues meurent sans fin",
    "La brume enveloppe tout",
    "Les ombres dansent et fuient",
    "Un rayon glisse et se perd",
    "Les nuages fuient au loin",
    "Les fleurs se penchent sans bruit",
    "Un soupir flotte et s’éteint",
    "Le ciel pâlit doucement",
    "Les feuilles tombent en paix",
    "Le murmure d’un ruisseau",
    "Le silence envahit tout",
    "Un instant fragile passe",
    "Les branches ploient sous le vent",
    "Un oiseau fuit le matin",
    "Le crépuscule descend",
    "Un rire lointain s’efface",
    "Les vagues caressent l’aube",
    "Un nuage couvre l’ombre",
    "La lumière fuit sans bruit",
    "Les collines se fondent loin",
    "Un éclat de lune brille",
    "Le vent murmure des chants",
    "Les étoiles s’effondrent",
    "Un soupir doux dans le vent",
    "Le silence du matin",
    "Un éclat de rire passe",
    "La lune veille en secret",
    "Les montagnes s’effacent",
    "Un murmure dans la brume",
    "Les ombres gagnent le sol",
    "Les fleurs ploient sous la pluie",
    "Les vagues chantent et s’en vont",
    "Le ciel s’assombrit doucement",
    "Les branches dansent et plient",
    "Un cri d’oiseau dans la nuit",
    "Un éclair traverse l’air",
    "La rosée brille un instant",
    "Les collines plongent en paix",
    "La pluie tombe en silence",
    "Les étoiles veillent là-haut",
    "Un souffle de vie s’éteint",
    "Les arbres se penchent doux",
    "Un voile de brume flotte",
    "Les feuilles parlent tout bas",
    "Un murmure calme la nuit",
    "Les collines se cachent loin",
    "Un instant de calme pur",
    "La lumière fond en paix",
    "Les vagues se retirent lent",
    "Les ombres glissent sans fin",
    "Le vent s'enroule et s'enfuit",
    "Un oiseau s’envole seul",
    "Le crépuscule descend",
    "Un parfum s’efface vite",
    "Les montagnes s’estompent",
    "Un sourire au loin se perd",
    "Le ruisseau coule sans bruit",
    "Le ciel se voile en douceur",
    "Les branches ploient sous la brume",
    "Un cri d'oiseau dans l'air frais",
    "Les étoiles glissent là-bas",
    "La brume s'éteint doucement",
    "Un reflet se perd en paix",
    "Les ombres s'étirent loin",
    "Un parfum s'évapore doux",
    "Les vagues s’effacent lent",
    "Le vent murmure aux collines",
    "Un souffle de vie s’évade",
    "Les nuages passent en paix",
    "Les étoiles s’éloignent",
    "Un instant de silence pur",
    "Les collines plongent en paix",
    "Les feuilles glissent au vent",
    "Un murmure glisse lent",
    "Les vagues embrassent l’ombre",
    "Un éclat brille en silence",
    "Les branches ploient doucement",
    "Les collines se taisent là",
    "Un nuage couvre la nuit",
    "Les étoiles fuient l'aurore",
    "La lumière fond et fuit",
    "Un soupir s’évanouit",
    "Les montagnes se fondent loin",
    "Un instant de paix fragile",
    "La pluie lave les sentiers",
    "Un souffle éteint les ombres",
    "Les collines s’assombrissent",
    "Un oiseau vole et s’éteint",
    "Les étoiles veillent bas",
    "Un soupir dans le crépuscule",
    "Les feuilles tremblent et tombent",
    "Un murmure glisse en paix",
    "Les ombres embrassent tout",
    "Le ruisseau chante en secret",
    "La lumière danse en paix",
    "Les vagues se fondent loin",
    "Un éclat dans l'air du soir",
    "Les feuilles s'effacent là",
    "La nuit couvre les montagnes",
    "Les étoiles meurent en paix",
    "Les vagues chantent doucement",
    "Les collines se perdent",
    "Le silence de l'aube",
    "Un oiseau crie dans le vent",
    "Les vagues s’endorment là",
    "Les ombres caressent tout",
    "Le ciel s’efface en silence",
    "Les branches ploient et se taisent",
    "Un reflet d'étoile passe",
    "Les nuages se dispersent",
    "Un éclat de vie se perd",
    "Les collines plongent en paix",
    "Un souffle s'étend et fond",
    "La rosée tremble en silence",
    "Les fleurs ploient sous le vent",
    "Un instant de vie s’efface",
    "Les branches murmurent bas",
    "Un souffle calme la nuit",
    "Les collines plongent en paix",
    "Les étoiles s'estompent loin",
    "Un murmure éteint la mer",
    "Les vagues glissent sans fin",
    "Les nuages passent sans bruit",
    "Les collines plongent en paix",
    "Un éclat dans l'eau claire",
    "La pluie tombe en secret",
    "Les ombres gagnent la mer",
    "Les vagues s’effacent loin",
    "Un soupir embrasse l’aube",
    "Les montagnes plongent en paix",
    "Les feuilles tombent sans bruit",
    "Un instant s'efface là",
    "Les branches ploient sous l'aube",
    "Les nuages recouvrent tout",
    "Les collines plongent et se taisent",
    "Un éclat danse et s'éteint",
    "Les étoiles glissent lent",
    "Les vagues s'étirent loin",
    "Un souffle traverse l'ombre",
    "Les feuilles flottent légères",
    "Le ruisseau chante en paix",
    "Les étoiles meurent lentement",
    "Un éclat passe dans l'ombre",
    "La brume étreint les arbres",
    "Les collines plongent en paix",
    "Les nuages glissent loin",
    "Un parfum léger s'en va",
    "Les vagues murmurent lentement",
    "Les branches se courbent douces",
    "Un instant de vie fragile",
    "Les montagnes plongent lent",
    "Un cri d'oiseau dans l'ombre",
    "Les vagues s'effacent tout bas",
    "Les étoiles veillent là-haut",
    "Un éclat dans l'air du soir",
    "Les feuilles glissent au vent",
    "Les collines plongent en paix",
    "Un murmure calme l'aube",
    "Les vagues se perdent loin",
    "Les étoiles meurent en paix",
    "Un souffle embrasse la brume",
    "Les nuages s’étendent là",
    "Les branches tremblent légères",
    "Un parfum flotte en secret",
    "Les collines plongent en paix",
    "Les feuilles volent légères",
    "Les étoiles dansent là-haut",
    "Les vagues se retirent lentes",
    "Un éclat brille dans l'ombre",
    "Les ombres embrassent tout",
    "La lumière tremble en paix",
    "Un instant passe et se perd",
    "Les branches murmurent tout bas",
    "Les collines plongent en paix",
    "Les étoiles veillent sans bruit",
    "Un parfum de nuit se perd",
    "Les vagues chantent et se taisent",
    "Les montagnes plongent en paix",
    "Les feuilles frémissent là",
    "Un souffle emporte la nuit",
    "Les collines plongent en paix",
    "Un reflet danse et disparaît",
    "Les nuages fuient le matin",
    "Les étoiles glissent et se taisent",
    "Les vagues meurent tout bas",
    "Les branches dansent en paix",
    "Un parfum s'efface doucement",
    "Les collines plongent en paix",
    "Les étoiles s'effacent lentement",
    "Un éclat embrasse l'aube",
    "Les vagues se taisent tout bas",
    "Les nuages se fondent là",
    "Les collines plongent en paix",
    "Un instant doux s'échappe",
    "Les feuilles frémissent en paix",
    "Les vagues embrassent tout bas",
    "Les branches murmurent et se taisent"
};

#define SIZE_LINES_7_SYLLABLES_LINE2 (sizeof(LINES_7_SYLLABLES_LINE2) / sizeof(LINES_7_SYLLABLES_LINE2[0]))

#endif // LINE2_LIBRARY_H
