#ifndef LINE3_LIBRARY_H
#define LINE3_LIBRARY_H

const char* LINES_5_SYLLABLES_LINE3[] = {
    "Un soupir s’éteint",
    "La vague se perd",
    "Un murmure doux",
    "L'étoile s’efface",
    "Ombre qui vacille",
    "Le parfum s’en va",
    "L'oiseau disparaît",
    "L’ombre d’un instant",
    "Rosée du matin",
    "La lumière fuit",
    "Brise sur la mer",
    "Un silence doux",
    "Feuilles qui tombent",
    "L'éclair s’estompe",
    "La brume descend",
    "Un souffle léger",
    "Le ciel s’assombrit",
    "Le temps se retire",
    "Un rêve se fond",
    "Le matin hésite",
    "Étoiles lointaines",
    "Un voile de brume",
    "La nuit s’évapore",
    "Le cri d’un oiseau",
    "Les ombres s'étirent",
    "La rosée s’éteint",
    "L'ombre des nuages",
    "Les étoiles fuient",
    "Un souffle de paix",
    "Un instant s’efface",
    "Le vent se retire",
    "Un écho lointain",
    "Un rire s’échappe",
    "Brume sur l’étang",
    "Le ciel se voile",
    "Un pas dans la neige",
    "L’ombre d’un pin",
    "La mer se retire",
    "Les nuages passent",
    "Un cri dans la nuit",
    "Les feuilles volent",
    "Un murmure court",
    "Douceur éphémère",
    "Le soir s’éteint",
    "Un reflet s’efface",
    "Les étoiles tombent",
    "Le silence glisse",
    "Le souffle s’efface",
    "Un soupir discret",
    "L’aube hésitante",
    "Les branches dansent",
    "La rosée s’efface",
    "L'ombre s'incline",
    "Un oiseau s’enfuit",
    "Un parfum léger",
    "La lumière tremble",
    "Les étoiles brillent",
    "La brume s’étend",
    "Un cri qui s'efface",
    "Un souffle d’air pur",
    "L'instant s'en va",
    "La nuit se tait",
    "Un murmure fin",
    "Le silence doux",
    "Un rêve en écho",
    "Le vent s'enroule",
    "L'éclair d’un soir",
    "L’ombre douce fuit",
    "Brume dans les bois",
    "Un frisson léger",
    "Un parfum de pin",
    "Les feuilles mortes",
    "Le ruisseau s'endort",
    "La lune descend",
    "Le ciel se vide",
    "Un rêve s’efface",
    "Le soir s'allonge",
    "L’étoile disparaît",
    "Le jour s’enfuit",
    "Les ombres passent",
    "La nuit s'installe",
    "Les nuages fondent",
    "Un cri s’éteint",
    "L'aube se retire",
    "Les feuilles tombent",
    "Un murmure faible",
    "Le vent qui se tait",
    "Un instant léger",
    "La pluie s’étire",
    "Un sourire passe",
    "Le jour s'efface",
    "Le calme revient",
    "Les ombres glissent",
    "Un souffle doux",
    "L’écho du silence",
    "Un rire perdu",
    "Le crépuscule",
    "Un reflet flou",
    "La brume danse",
    "Le murmure fuit",
    "Un soupir tendre",
    "L’étoile s’en va",
    "Un instant fragile",
    "Les feuilles vibrent",
    "La nuit étouffe",
    "Un cri dans le vent",
    "La lumière dort",
    "Un parfum flottant",
    "Les ombres s'effacent",
    "Un instant pur",
    "Les nuages tombent",
    "Un frisson passe",
    "La rosée brille",
    "Un oiseau s’élance",
    "Les branches bougent",
    "L'ombre s'enroule",
    "Un soupir glisse",
    "Les étoiles dansent",
    "Un vol disparaît",
    "La lune s’enfuit",
    "Le silence court",
    "Un murmure lent",
    "Le jour s'endort",
    "Un souffle secret",
    "Les ombres pleurent",
    "Le matin passe",
    "L'éclair s'efface",
    "Un oiseau se tait",
    "Les nuages fuient",
    "La rosée fond",
    "Les fleurs s'inclinent",
    "Un murmure passe",
    "Les vagues glissent",
    "Le soleil pâlit",
    "Un instant calme",
    "Les étoiles voilent",
    "La mer s’enfuit",
    "Le jour s'effondre",
    "Les nuages flottent",
    "Un soupir ténu",
    "Les ombres se perdent",
    "Un rêve s'éveille",
    "Les branches tremblent",
    "L'ombre disparaît",
    "Un cri d'oiseau",
    "Un parfum léger",
    "Le ciel s’incline",
    "Le murmure fond",
    "Un frisson se lève",
    "Le soleil tombe",
    "Un instant d’ombre",
    "Un vol s'éloigne",
    "Les vagues retombent",
    "Un murmure vague",
    "La lumière luit",
    "Les feuilles frémissent",
    "Le silence naît",
    "Un reflet perdu",
    "Les nuages glissent",
    "Les fleurs se penchent",
    "Un souffle ancien",
    "Le ciel s'endort",
    "La brume danse",
    "Les vagues murmurent",
    "Un cri en écho",
    "Les étoiles filent",
    "La lune s’éteint",
    "Le vent passe vite",
    "Les ombres s’endorment",
    "Un éclat de vie",
    "Un sourire en rêve",
    "Le jour qui recule",
    "Le calme revient",
    "Un éclat d’eau",
    "La lueur s'éteint",
    "Un rire lointain",
    "La vague s'éloigne",
    "Un murmure doux",
    "Le vent qui se tait",
    "Un instant passe",
    "L’ombre sous la pluie",
    "Un soupir perdu",
    "Les étoiles fondent",
    "Un parfum s'échappe",
    "Le silence coule",
    "La pluie sur les feuilles",
    "Un souffle finit",
    "Les ombres s'étendent",
    "La lune apparaît",
    "Le matin s'efface",
    "Un murmure sec",
    "Le rêve descend",
    "Un instant de paix",
    "Le chant du matin",
    "Le soir qui murmure",
    "Un écho lointain",
    "Les nuages rampent",
    "Un vol se tait",
    "Le vent s'efface",
    "Les étoiles meurent",
    "La mer s'apaise",
    "Un éclat de lune",
    "Un rêve s'attarde",
    "Le murmure part",
    "La nuit s'étire",
    "Le silence tombe",
    "Les vagues dansent",
    "Un parfum s'envole",
    "Les nuages passent",
    "La lumière glisse",
    "Les branches frissonnent",
    "Le jour se tait",
    "Un souffle de fin",
    "Les ombres s’étendent",
    "Un cri retombe",
    "La lune tremble",
    "Un éclat perdu",
    "Les étoiles se taisent",
    "Un soupir passe",
    "Les ombres rampent",
    "Un murmure coule",
    "Les nuages fondent",
    "Un rêve flétri",
    "Un instant s'efface",
    "Le soleil pâlit",
    "Un parfum fuit",
    "Les vagues se taisent",
    "Le jour s'étiole",
    "Un murmure éclate",
    "Les fleurs flétrissent",
    "Les étoiles roulent",
    "La brume vole",
    "Les branches cèdent",
    "Un frisson éteint",
    "Les ombres roulent",
    "Le silence rampe",
    "Un sourire d’aube",
    "Les vagues se brisent",
    "La rosée meurt",
    "Un murmure de paix",
    "Les feuilles craquent",
    "La nuit grandit",
    "Les fleurs s’évanouissent",
    "Le rêve s'étire"
};

#define SIZE_LINES_5_SYLLABLES_LINE3 (sizeof(LINES_5_SYLLABLES_LINE3) / sizeof(LINES_5_SYLLABLES_LINE3[0]))

#endif // LINE3_LIBRARY_H
