#ifndef LINE1_LIBRARY_H
#define LINE1_LIBRARY_H

const char* LINES_5_SYLLABLES_LINE1[] = {
    "Brise du matin",
    "L'éclair dans la nuit",
    "Feuille qui s'envole",
    "L'ombre qui se perd",
    "Rosée sur les fleurs",
    "Un souffle s'efface",
    "Étoile qui fuit",
    "La vague s'éteint",
    "Parfum éphémère",
    "Vent doux sur la mer",
    "Silence des bois",
    "Lumière qui tombe",
    "L'oiseau disparaît",
    "Le cri d'un lointain",
    "Flamme vacillante",
    "Un rire lointain",
    "Nuage qui passe",
    "Un reflet fragile",
    "Dernière lumière",
    "La pluie se dissipe",
    "Éclat d'un instant",
    "Un pas dans la brume",
    "Un rêve qui fond",
    "L'ombre des nuages",
    "Bourgeon dans la nuit",
    "Un écho s'endort",
    "Soleil qui décline",
    "Odeur de la pluie",
    "Les fleurs qui tombent",
    "Ombre dans le vent",
    "Souffle sur la neige",
    "Un vol égaré",
    "Léger crépuscule",
    "Un murmure court",
    "Dernier chant d'oiseau",
    "La feuille se pose",
    "Silence d'hiver",
    "Un rayon glissant",
    "Vapeur sur l'étang",
    "Un reflet s'éteint",
    "Une trace fond",
    "Vent de fin d'été",
    "L'écume se perd",
    "Crépitement doux",
    "Un frisson se tait",
    "L'aube se dissout",
    "Flocon suspendu",
    "Bruit d'une goutte",
    "Trace dans le sable",
    "Ombre vacillante",
    "Dernier souffle chaud",
    "Le feu s'éteint",
    "Un éclat furtif",
    "Le soir descend",
    "Un soupir léger",
    "Éclair dans les cieux",
    "Bourdonnement fin",
    "Lent soupir du vent",
    "L'instant s'échappe",
    "Un voile léger",
    "Nuage effacé",
    "Douceur d'un instant",
    "Un rayon épars",
    "Un cri s'éloigne",
    "Écho dans le soir",
    "Le calme s'installe",
    "Un souffle furtif",
    "Parfum qui s'en va",
    "La fleur se plie",
    "Ombre d'une main",
    "Un reflet brisé",
    "La lune s'efface",
    "Lumière tremblante",
    "Un éclat de voix",
    "Vent dans les branches",
    "La rosée tombe",
    "Un pas se perd",
    "Chaleur qui s'enfuit",
    "Odeur de pin",
    "Le jour s'étire",
    "Ruisseau qui s'efface",
    "Ombre des collines",
    "Silence fragile",
    "Un chant éteint",
    "La brume danse",
    "Pluie sur les pierres",
    "Un cri dans le vent",
    "Soleil sur l'eau",
    "L'éclat d'un ruisseau",
    "Le ciel qui change",
    "Vibration légère",
    "L'écho s'estompe",
    "Un pas disparaît",
    "Les feuilles tombent",
    "Un frisson glisse",
    "L'aube hésitante",
    "Un murmure doux",
    "Flamme d'un moment",
    "Un rire qui file",
    "Dernier souffle pur",
    "Les ombres bougent",
    "Lueur du matin",
    "Un rêve éphémère",
    "Étoiles qui s'en vont",
    "Feuilles dans la brise",
    "Le silence passe",
    "Un nuage flou",
    "Brise d'une nuit",
    "La cendre s'éteint",
    "Reflet d'une main",
    "Ombre qui revient",
    "Un murmure froid",
    "Brise d'automne",
    "Sable sous les pas",
    "Légère lueur",
    "Les branches dansent",
    "L'écume retombe",
    "Un souffle doux",
    "Les étoiles fuient",
    "Un éclat dans l'air",
    "Poussière légère",
    "L'ombre effacée",
    "Brume sur les champs",
    "Un oiseau s'échappe",
    "Lueur dans les bois",
    "L'ombre d'une fleur",
    "L'herbe s'incline",
    "Un voile se lève",
    "Le crépuscule",
    "Un souffle d'ombre",
    "Un instant flottant",
    "Le temps s'efface",
    "L'écho d'un cri",
    "Le matin hésite",
    "Un silence pur",
    "Parfum de rosée",
    "Les nuages glissent",
    "Ombres dans l'eau",
    "Un reflet fragile",
    "La vague retombe",
    "Poussière dans l'air",
    "Le vent sur les feuilles",
    "Bourgeon qui se ferme",
    "Un pas sur le sol",
    "L'ombre d'un instant",
    "La lumière fuit",
    "Un murmure en fuite",
    "Le jour s'endort",
    "L'arbre s'incline",
    "Le ciel s'éclaircit",
    "Un frisson passe",
    "Les bruits s'effacent",
    "La lune hésitante",
    "Un rêve évanoui",
    "Parfum d'une nuit",
    "L'ombre glissante",
    "Dernier rayon doux",
    "Les étoiles passent",
    "La trace se fond",
    "Un soupir ténu",
    "Brume sur la mer",
    "Douceur de l'instant",
    "Un souffle qui fuit",
    "Le soir qui s'efface",
    "Un cri dans le ciel",
    "Les ombres s'en vont",
    "L'éclat d'un rire",
    "L'instant se perd",
    "Le jour s'échappe",
    "Un murmure bas",
    "Les ombres fondent",
    "Brise d'une étoile",
    "La lumière glisse",
    "Un parfum de fin",
    "La nuit descend",
    "Un écho lointain",
    "Le calme tombe",
    "La rosée s'efface",
    "Brise d'un matin",
    "L'ombre des pins",
    "Un reflet qui meurt",
    "L'éclair du lointain",
    "Les vagues reculent",
    "Le souffle du soir",
    "Un nuage court",
    "Le crépuscule passe",
    "L'ombre s'étire",
    "Dernier vol d'oiseau",
    "Brume sur le lac",
    "Un éclat perdu",
    "Souffle d'une nuit",
    "La lumière change",
    "Ombre sous les cieux",
    "Un rayon hésite",
    "La vague retourne",
    "Soleil qui faiblit",
    "Douceur d'un son",
    "L'écho d'un murmure",
    "Les bruits lointains",
    "Un dernier éclat",
    "La lumière s'en va",
    "Un rire éphémère",
    "Les ombres volent",
    "Dernier reflet clair",
    "L'instant évanoui",
    "Un souffle d'air",
    "Le jour se retire",
    "Un rayon perdu",
    "Dernière trace",
    "La mer se retire",
    "Les étoiles passent",
    "Éclair au loin",
    "Un cri qui retombe",
    "Le vent s'éteint",
    "Éclat du matin",
    "Un murmure va",
    "Les feuilles mortes",
    "Un vol d'oiseau",
    "Brise douce et lente",
    "Le dernier frisson",
    "L'ombre disparaît",
    "Un rire passe",
    "Le souffle s'en va",
    "Un silence tombe",
    "Les nuages s'éloignent",
    "L'eau se retire",
    "Lueur vacillante",
    "Le jour s'achève",
    "Une fleur plie",
    "Un instant d'éclair",
    "Les ombres dansent",
    "La rosée s'évapore",
    "Un son ténu",
    "L'instant glisse",
    "Un murmure d'ombre",
    "Étoile s'efface",
    "Odeur de la brume",
    "Le cri du lointain",
    "Un frisson au loin",
    "Dernier vol dans l'air"
};

#define SIZE_LINES_5_SYLLABLES_LINE1 (sizeof(LINES_5_SYLLABLES_LINE1) / sizeof(LINES_5_SYLLABLES_LINE1[0]))

#endif // LINE1_LIBRARY_H
